version: '3'

services:
  nats:
    container_name: nats
    restart: always
    image: nats-streaming:latest
    ports:
      - 4222:4222 # is for clients.
      - 8222:8222 # is an HTTP management port for information reporting.
    command: "-SDV"
